layout_spectrum: 0.2425532
name: TheCrazyPT
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5787234
color:
  brandStrength: 0.6085106
  lightness: 0.4851064
  saturation: 0.07398286
  rhythmicContrast: 0.7727805
  brandColors:
    - '#010002'
    - '#202E56'
    - '#7A707D'
    - '#F3882D'
    - '#B63411'
