layout_spectrum: 0.9489362
name: TheCrazyPT
color:
  brandStrength: 0.6085106
  saturation: 0.07398286
  brandColors:
    - '#FFFFFF'
    - '#0C0B0F'
    - '#555449'
    - '#99706D'
    - '#FFB4E9'
  lightness: 0.4851064
  rhythmicContrast: 0.7727805
typography_spectrum: 0.2599598
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
