layout_spectrum: 0.7308711
typography_spectrum: 0.2599598
color:
  lightness: 0.4851064
  brandStrength: 0.6085106
  saturation: 0.07398286
  rhythmicContrast: 0.7727805
  brandColors:
    - '#FFFFFF'
    - '#0C0B0F'
    - '#555449'
    - '#99706D'
    - '#FFB4E9'
name: TheCrazyPT
